Install itest before running build
I got a failure because there is at least one package that is only
installed in the itest directory.

https://github.com/cdk-turnkey/stackname/runs/3873953387?check_suite_focus=true

Run npm run build --if-present
  npm run build --if-present
  shell: /usr/bin/bash -e {0}

> @cdk-turnkey/stackname@2.0.0 build
/home/runner/work/stackname/stackname
> tsc

npm ERR! code ELIFECYCLE
Error: itest/it01/bin/it01.ts(3,22): error TS2307: Cannot find module
'@aws-cdk/core' or its corresponding type declarations.
npm ERR! errno 2
npm ERR! @cdk-turnkey/stackname@2.0.0 build: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @cdk-turnkey/stackname@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-10-12T18_08_26_706Z-debug.log
Error: itest/it01/lib/it01-stack-a.ts(1,22): error TS2307: Cannot find
module '@aws-cdk/core' or its corresponding type declarations.
Error: itest/it01/lib/it01-stack-a.ts(2,21): error TS2307: Cannot find
module '@aws-cdk/aws-s3' or its corresponding type declarations.
Error: itest/it01/test/it01.test.ts(5,8): error TS2307: Cannot find
module '@aws-cdk/assert' or its corresponding type declarations.
Error: itest/it01/test/it01.test.ts(6,22): error TS2307: Cannot find
module '@aws-cdk/core' or its corresponding type declarations.
Error: Process completed with exit code 2.