Set test env as node in itest test
Still flailing at the error:

> ReferenceError: TextDecoder is not defined

which is happening in GitHub Actions, but not locally.

https://stackoverflow.com/a/69734807/2260686